# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa070d1b80ee444cb4f439dc776a477e8b58b1eea5704692204a2ad0d4f399c9a2a0d083a90332e890043f4352a4c6be2d763410166317b3982cb132cabd7ede

test:
  secret_key_base: 5b1877e435dc8e6bb037f874ef5bba32d4e0fff24659ce450280467e0a716546df86e598e36aa60ffdaf845f9fdbbe39ccb019478c941327bb70caaa3b67aa5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
